{{- /* Translate memory limits into ops instructions, if present */}}

{{- define "ops.resources" }}
  {{- $root := index . 0 }}
  {{- $values_name := index . 1 }}
  {{- $bosh_name := index . 2 }}

  {{- $resources := index $root.Values $values_name }}
  {{- range $ig_name, $ig := $resources }}
    {{- range $job_name, $job := $ig }}
      {{- range $process_name, $resource := $job }}
        {{- if $root.Values.features.cpu_limits.enabled }}
          {{- if $resource.cpu.limit }}
- type: replace
  path: /{{ $bosh_name }}/name={{ $ig_name }}/jobs/name={{ $job_name }}/properties?/quarks/bpm/processes/name={{ $process_name }}/limits/cpu
  value: {{ $resource.cpu.limit }}m
          {{- end }}

          {{- if $resource.cpu.request }}
- type: replace
  path: /{{ $bosh_name }}/name={{ $ig_name }}/jobs/name={{ $job_name }}/properties?/quarks/bpm/processes/name={{ $process_name }}/requests/cpu
  value: {{ $resource.cpu.request }}m
          {{- end }}
        {{- end }}

        {{- if $root.Values.features.memory_limits.enabled }}
          {{- if $resource.memory.limit }}
- type: replace
  path: /{{ $bosh_name }}/name={{ $ig_name }}/jobs/name={{ $job_name }}/properties?/quarks/bpm/processes/name={{ $process_name }}/limits/memory
  value: {{ $resource.memory.limit }}Mi
          {{- end }}

          {{- if $resource.memory.request }}
- type: replace
  path: /{{ $bosh_name }}/name={{ $ig_name }}/jobs/name={{ $job_name }}/properties?/quarks/bpm/processes/name={{ $process_name }}/requests/memory
  value: {{ $resource.memory.request }}Mi
          {{- end }}
        {{- end }}
      {{- end }}

      {{- if not $job }}
- type: replace
  path: /{{ $bosh_name }}/name={{ $ig_name }}/jobs/name={{ $job_name }}?/properties/quarks/bpm/processes
  value: []
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}

{{- include "ops.resources" (list $ "resources" "instance_groups") }}
{{- include "ops.resources" (list $ "addon_resources" "addons") }}
