# This configuration tree specifies the default resource limits and requests
# for the kubecf instance groups and jobs.
#
# Syntax: See `chart/values.schema.yaml`
#
# NOTE: Missing instance groups and/or jobs are filled using data from
#  	the jobs tree.
#
#	Missing instance groups are added with `'$default': 2048`.
#       This is a very generous global limit. Stricter limits must be
#       specified here.
#
#	Instance groups without '$default' are extended with `'$default': 2048`.
#	Missing jobs are added with nil value -> This invokes the '$default'
#
#	This is all handled by `_resources.update` in `chart/templates/_resources.tpl`.
#
# NOTE 2: We need process names per job per group. This information is taken
#         from the data in `chart/config/jobs.yaml`, the per-job `processes` key.
#
#         All the processes of a job are given the same limit.
#
# NOTE 3: The `as*` groupds are for autoscaler. As they do not exist
# 	  in cf-deployment the auto-fill will not work for them. Thus
# 	  them being listed in full.
#
# The information from here is used by the helm templating creating
# ops instructions from the resource configuration for jobs to determine
# which jobs to ignore in the current deployment, in a generic
# manner. I.e not mixed into the templating code itself.
#
# All relevant supporting and using files are
#
# - chart/config/jobs.yaml			Job conditions
# - chart/config/resources.yaml			Self
# - chart/operations/resource-limits.yaml	Transform resource config to ops
# - chart/templates/_jobs.tpl			Take conditions and complete/resolve
# - chart/templates/_resources.tpl		Take self and complete
# - chart/templates/bosh_deployment.yaml	Reference the new config map
# - chart/templates/ops.yaml			Wrap `resources-limits.yaml` into config map
# - chart/values.schema.yaml			Job, resource config structure spec

# # ## ### ###### ######## ############# #####################

resources:
  asactors:
    '$default': 30
    operator: ~
    scalingengine: ~
    scheduler: 800
  asapi:
    '$default': 30
    golangapiserver: ~
    metricsforwarder: ~
    route_registrar: ~
  asdatabase:
    '$default': 30
    postgres: 300
  asmetrics:
    '$default': 30
    eventgenerator: ~
    metricsserver: ~
  asnozzle:
    '$default': 40
    metricsgateway: ~

  api:
    '$default': 550
    cloud_controller_ng: 2048
  cc-worker:
    '$default': 350
  credhub:
    '$default': 15
    credhub: 750
  diego-api:
    '$default': 50
  diego-cell:
    '$default': 40
    garden: 2048
    rep: 3072
  doppler:
    '$default': 40
    doppler: 70
  log-api:
    '$default': 100
  log-cache:
    '$default': 40
    log-cache: 2048
  nats:
    '$default': 30
  router:
    '$default': 100
  scheduler:
    '$default': 40
    cc_deployment_updater: 260
    cloud_controller_clock: 360
  singleton-blobstore:
    '$default': 330
  tcp-router:
    '$default': 60
  uaa:
    '$default': 30
    uaa: 1100
