{{- include "_config.load" $ }}
{{- $stemcell := $.Values.defaults.stemcell }}

- type: replace
  path: /stemcells/alias=default
  value:
    alias: default
    os: {{ $stemcell.os | quote }}
    version: {{ $stemcell.version | quote }}

{{- range $addon_name, $addon := $.Values.addons }}
  {{- /* All jobs in the addon have the same .condition value */}}
  {{- $job_name := $addon | keys | first }}
  {{- if index $addon $job_name "condition" }}
- type: replace
  path: /addons/name={{ $addon_name }}/include/stemcell/os=ubuntu-xenial/os
  value: {{ $stemcell.os | quote }}
  {{- end }}
{{- end }}
